name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  release_please:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          token: ${{ secrets.RELEASE_TOKEN }}
          changelog-types: '[{"type": "feat", "section": "Features", "hidden": false},{"type": "fix", "section": "Fixes", "hidden": false},{"type": "refactor", "section": "Refactor", "hidden": false}]'
